### ISSUE TITLE
Database import as cron script via template

### ISSUE THREAD

**Issue by joshuacherry** [RPI-HASS/ansible-role-csdt-django#3]
Implement a script via ansible template and use cron task to run script.

Similar to the below
```
- name: Creates weekly backup
  cron: minute="59" hour="23" weekday="fri"
        name: "Scheduled backup"
        cron_file: "postgresbackup"
        user: postgres
        job: "{{csdt_django_git_destination}}"/postgresbackup.sh  

- name: Script
  template:
    src: "templates/postgresbackup.sh.j2"
    dest: "{{csdt_django_git_destination}}"/postgresbackup.sh  
    mode: "0655"
```
The script will need to ssh to the prod server, backup the database, then rsync media files and import database to dev.
